### PR TITLE
ENHANCE: Add output formatting / presentation support for the LBCF in PDF and alternative HTML, as typesetted in LaTeX

### LINKED ISSUE #19: ENHANCE: Add support for source typesetting of the LBCF in LaTeX and desired formatted output docs.
This would be a really cool feature.  It would allow for convenient formatting into PDF or HTML without too much fancy work using Pdflatex, Htlatex, Tex4ht and other similar solutions.

### PR DESCRIPTION
**Pull request by njsch**
Closes #19.  See relevant issue for more info.

FYI @lwalen.

### CODE REVIEW

**Comment by njsch** [comment]
That last commit references the markdown, not the LaTeX!

**Comment by lwalen** [comment]
Wow, thank you! Would you like to update the README with links to these new files? If not, I can do that later.

What is the difference between the HTML files? Are they outputs of different LaTeX-to-HTML tools? It would be kind of nice to include instructions for producing them.

Thanks again!

**Comment by njsch** [comment]
@lwalen,
Yes, I can update the readme.

The Two HTML files are produced, one with HTLatex and the other one with Tex4ht.  Tex4ht doesn't work well on Windows and I couldn't even get it to work perperly in the MSYS2 subsystem / OS emulator I have installed to do some Unix/Linux-style stuff.  But if you use HTlatex, it's as simple as calling `htlatex <filename>` from within a text-based console / terminal.

**Comment by njsch** [comment]
@lwalen, update complete.

**Pull request merged**
