### PR TITLE
Update Markdown to include Scripture refs and TOC

### PR DESCRIPTION
**Pull request by njsch**
@lwalen, updated the Markdown to include Scripture references and a superficial but not adequately working table of contents, as it contains no in-page links.  However, we have a problem: Did you do what I think is called a rebase merge when you added my prior content? Because whenever I submit a PR now, it wants me to re-merge the same previous commits all over again.  I don't know what to do about this...

### CODE REVIEW

**Comment by njsch** [comment]
Hey @lwalen, I have updated the readme but had to remove the source files and output as a strategy for working around your potential re-base merge, or whatever it was you initially used when committing my content. Can you accept this PR and then I'll add the files back in and re-submit with another PR? Thanks.

For reference, I have added the ability to reference every paragraph of every chapter with the \label command using the book doc class and the preface and appendix have been added with signatories/subscribers.

**Comment by njsch** [comment]
This is how it should look according to [my own version](https://njschmidt.id.au/1689lbc) (without the preliminary personal note):

**Comment by lwalen** [comment]
Thanks! Could you make the markdown file a new file called something like `lbcf_with_references.md`? I think it would be nice to have both versions available.

Looks like there are conflicts in the readme, too.

I appreciate the additions!

**Comment by njsch** [comment]
> Thanks! Could you make the markdown file a new file called something like `lbcf_with_references.md`? I think it would be nice to have both versions available.

Ah, yep I'll do that, I get it now.

> Looks like there are conflicts in the readme, too.

Well, I've checked both readme files and I'm pretty sure mine has the same original content as yours but I've made a couple of additions. As previously stated, there's something about yours and my git workflows which are conflicting but we both don't seem to know why. If you manually accept all of my changes then you will still have everything you put in the readme yourself.

My concern here is mainly regarding line blaming. Out of curiosity, what are your default line-endings? Mine are set to commit Unix-style, checkout as-is.

> I appreciate the additions!

No worries, I have enjoyed it.

**Comment by njsch** [comment]
Okay, so it seems I can fix the conflicts myself. With that done, I'll create the two MD files.

**Comment by njsch** [comment]
@lwalen, all done. It should be okay for you to merge now.

**Pull request merged**
